name: login_checkin

on:  [ push ]
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: python_env
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: 'run'
        run: python action_task/.github/xmrth_checkin.py

