name: login_checkin

on:
  push:
    branches: 
      - master
  schedule:
      - cron: '0 14 * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: python_env
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: 'work'
        run: python ./xmrth_checkin.py

