# This is a basic workflow to help you get started with Actions

name: 定时任务
on:
	schedule:
		-cron: "0 6 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: xmrth checkin
				uses: actions/setup-python@v2
				with:
					python-version: 3.9
        		run: |
          			curl https://xmrth.fun/user/checkin
		  			headers: {Cookie: uid=3703; email=458137665%40qq.com; key=135be4e5686b37772b346eb7fc6355073afef37348107; ip=dc4e6b99511bd34f3a29ef94e819d262; expire_in=1689236180; crisp-client%2Fsession%2F5690d3a5-53e4-435e-a52b-12af296b5cd9=session_eabbd0c9-d33f-44e5-abc6-0795e6c5a073; crisp-client%2Fsession%2F5690d3a5-53e4-435e-a52b-12af296b5cd9%2F9c805a3b-7bac-39ff-9728-7520af5fe7e4=session_eabbd0c9-d33f-44e5-abc6-0795e6c5a073}
					
					
				
				
					
