# This is a basic workflow to help you get started with Actions

name: 定时任务
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: xmrthCheckin
		uses: actions/setup-python@v2
		with:
			python-version: 3.9
        	run: |
			bash xmrth_checkin.sh
					
				
				
					
