# This is a basic workflow to help you get started with Actions

name: 定时任务
on:
	schedule:
		-cron: "0 6 * * *"
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: set up python
				uses: actions/setup-python@v2
				with:
					python-version: 3.9
			-name: Install dependecies
        run: |
          python -m pip install --upgrade pip
      	  pip install requests
					
					
				
				
					
