name: login_checkin
on:  
  push:
    branches: [ main ]
  schedule:
    - cron: '0 15 * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - name: python_env
        uses: actions/setup-python@2
        with:
          python-version: 3.9.18
      - name: 'Install requirements'
        run: |
            pip install --upgrade pip
            pip install -r ./requirements.txt
      - name: 'run'
        env:
          username: ${{ secrets.XMRTH_LOGIN_USER}}
          passwd: ${{secrets.XMRTH_LOGIN_PASSWD}}
        run: |
          echo 
          python ./xmrth_checkin.py

