name: login_checkin

on:  [ push ]
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: python_env
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: 'run'
        run: |
          echo 
          python xmrth_checkin.py

