# This is a basic workflow to help you get started with Actions

name: 定时任务
on: [push]
  # schedule:
  #   - cron '0 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
		  - uses: actions/setup-python@v1
		    with:
          python-version: 3.9
        run: |
          python ./xmrth_checkin.py
            
				
				
					
